# Generated by Django 5.2.7 on 2025-10-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_pagevisit_browser_pagevisit_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttonclick',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='country',
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='os',
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='session_id',
        ),
    ]
