# Generated by Django 5.2.7 on 2025-10-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название достижения')),
                ('number', models.CharField(max_length=20, verbose_name='Число/процент')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='Иконка (эмодзи)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название преимущества')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='⭐', max_length=10, verbose_name='Иконка (эмодзи)')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='Текст бейджа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='🔧', max_length=10, verbose_name='Иконка (эмодзи)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Хакасская газовая компания', max_length=200, verbose_name='Название компании')),
                ('phone', models.CharField(default='+7 (913) 442-57-77', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='manyakin1975@mail.ru', max_length=254, verbose_name='Email')),
                ('address', models.TextField(default='г. Абакан, Ташебинский промышленный узел, промплощадка Абаканвагонмаш территория, 77', verbose_name='Адрес')),
                ('working_hours', models.CharField(default='Пн-Пт: 8:00-17:00, экстренно 24/7', max_length=100, verbose_name='Режим работы')),
                ('hero_title', models.CharField(default='Надежная поставка газа в Хакасии', max_length=200, verbose_name='Заголовок главной секции')),
                ('hero_subtitle', models.TextField(default='Официальный дилер газа с полным спектром услуг: от заправки газгольдеров до монтажа оборудования', verbose_name='Подзаголовок главной секции')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
