# Generated by Django 5.2.7 on 2025-10-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('number', models.CharField(max_length=20, verbose_name='Число')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='📊', max_length=10, verbose_name='Иконка (эмодзи)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Статистика покрытия',
                'verbose_name_plural': 'Статистика покрытия',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название точки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Точка доставки',
                'verbose_name_plural': 'Точки доставки',
            },
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='additional_telephone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
    ]
